name: Deploy INeedToLearnK8s

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  TF_TOKEN: ${{ secrets.TF_TOKEN }}
  TF_VERSION: ${{ vars.TF_VERSION }}
  TF_AWS_PROVIDER_VERSION: ${{ vars.TF_AWS_PROVIDER_VERSION }}
  TG_TF_REGISTRY_TOKEN: ${{ secrets.TF_TOKEN }}

jobs:
  job-dev-test:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_ENV: DEV
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install curl wget zip unzip -y
      - name: Install Infracost
        run: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/${{ vars.TF_VERSION }}/terraform_${{ vars.TF_VERSION }}_linux_amd64.zip
          unzip terraform_${{ vars.TF_VERSION }}_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin
          terraform --version
      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ vars.TG_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version
      - name: Configure Terraform credentials
        run: |
          cat <<EOF >> ~/.terraformrc
          credentials "app.terraform.io" {
              token = "${{ secrets.TF_TOKEN }}"
          }
          EOF
      - name: Configure AWS credentials
        run: |
          mkdir ~/.aws
          cat <<EOF >> ~/.aws/credentials
          [default]
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          cat <<EOF >> ~/.aws/config
          [default]
          region=${{ vars.AWS_REGION }}
          EOF
      - name: Run Infracost and Terragrunt plan
        working-directory: infra
        run: |
          infracost breakdown --path .
          terragrunt plan
